[formatter]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh"]
options = ["-bn", "-ci", "-sr", "-i", "2", "-s", "-w"]

[formatter.prettier]
command = "prettier"
includes = ["*.md"]
options = ["--write"]

[formatter.taplo]
command = "taplo"
includes = ["*.toml"]
options = ["fmt"]
