name: "CI"

on:
  push:
    branches:
      - "*"

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build the flake
        run: |
          # Github Action runners do not support M1 yet.
          nix run nixpkgs#sd 'system = "aarch64-darwin"' 'system = "x86_64-darwin"' flake.nix
          nix run nixpkgs#nixci
